### ISSUE TITLE
error adding pmu in outputstream

### ISSUE THREAD

**Issue by pietropau** [GridProtectionAlliance/openPDC#4] opened 2016-04-27 09:59 UTC
When you setup new concentrated outputstream, an exception has been thrown during pmu adding  wizard .

Openpdc version:   2.2.29.0
.Net Runtime Version:  4.0.30319.42000
Mysql version: 5.7.12
Mysql connector NET version: 6.9.8
OS: Windows 7 professional

![openpdcmanager_error](https://cloud.githubusercontent.com/assets/18598157/14848658/0aee03be-0c6f-11e6-8927-2b4575c9aca9.PNG)

[error_concentrator_output_stream.txt](https://github.com/GridProtectionAlliance/openPDC/files/238395/error_concentrator_output_stream.txt)

Thanks,
Pietro

**Comment by ritchiecarroll** [comment] 2016-04-27 10:02
Looks like an issue with MySql, we will take a look...

**Comment by StephenCWills** [comment] 2016-04-27 14:10
This issue caused by the introduction of the VIRTUAL reserved keyword in MySQL version 5.7.6.
http://dev.mysql.com/doc/refman/5.7/en/keywords.html#ftn.idm140039936521520

This issue has been fixed in the latest code for GSF.
https://github.com/GridProtectionAlliance/gsf/commit/3dbac691bd2f03e565c591be07539a4b748647c5

The fix will show up in the next nightly build of openPDC (v2.2.30).

**Closed by StephenCWills** 2016-04-27 14:10 UTC
Labels: bug

**Comment by ritchiecarroll** [comment] 2016-04-27 15:55
BTW - nightly builds occur every night (from a US Eastern time-zone perspective) any time there have been check-ins during the day. You can download the openPDC nightly build from here:

https://www.gridprotectionalliance.org/NightlyBuilds/openPDC/Beta-VS2012/Synchrophasor.Installs.zip
