### ISSUE TITLE
ADAPTER CALCULATIONS RECURRENT FAIL 

### ISSUE THREAD

**Issue by cosimopis** [GridProtectionAlliance/openPDC#9] opened 2016-05-12 08:04 UTC
Hallo,

I tested extensively some adapters both already available as default in OpenPdc and customized by myself. I found a recurrent error log which is a bit strange (I attach screenshoot of the log page and details of the newest) due to the type of calculations made.
Actually both (for instance) for "Manage power calculations" and a simply "DividebySqrt(3)" adapter it says: GSF.PhasorProtocols  --> System.DivideByzeroException

Both in power calculation and voltage conversion (phase to phase -->phase to ground) there are no division by zero?

Could you help us to fix?

Best regards,

Cosimo
[log_fail_detail.docx](https://github.com/GridProtectionAlliance/openPDC/files/260822/log_fail_detail.docx)
![log_adapter_fail](https://cloud.githubusercontent.com/assets/19221022/15207855/ec401496-1828-11e6-9aeb-399a83509815.png)

**Comment by StephenCWills** [comment] 2016-05-13 12:59
Hello Cosimo,

Your log file suggests this was a minor logic error in the IEEE 1344 frame parser that was related to the recent timestamp fix and caused by an incorrectly handled edge case. I've applied a fix for the edge case which I believe should fix the problem.

https://github.com/GridProtectionAlliance/gsf/commit/1c59ff7da59de78080b01a40047bd47a169fdd5d

The fix will be available in the next nightly build version (v2.2.46). I'm closing the issue for now. If you continue to encounter the error in the future, please reopen the issue.

Thanks,
Stephen

**Closed by StephenCWills** 2016-05-13 12:59 UTC
Labels: bug

**Comment by cosimopis** [comment] 2016-05-13 13:01
Great!

**Comment by Vtern** [comment] 2016-05-13 13:24
When it will be available 2.2.46 version Stephen?

**Comment by StephenCWills** [comment] 2016-05-13 14:16
I'll kick off a build. It should be available in 10 or 15 minutes.

**Comment by cosimopis** [comment] 2016-05-13 14:18
Nice!
Thanks
Cosimo

Da: Stephen C. Wills [mailto:notifications@github.com]
Inviato: venerdì 13 maggio 2016 16:16
A: GridProtectionAlliance/openPDC <openPDC@noreply.github.com>
Cc: Pisani Cosimo (Terna) <cosimo.pisani@terna.it>; Author <author@noreply.github.com>
Oggetto: Re: [GridProtectionAlliance/openPDC] ADAPTER CALCULATIONS RECURRENT FAIL (#9)


I'll kick off a build. It should be available in 10 or 15 minutes.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/GridProtectionAlliance/openPDC/issues/9#issuecomment-219055642>
Questo messaggio (allegati eventuali compresi) contiene informazioni del Gruppo Terna che devono essere utilizzate esclusivamente dai destinatari in relazione alle finalità per le quali sono state inviate. È vietata qualsiasi forma di divulgazione senza l’esplicito consenso di Terna. Qualora questa e-mail sia stata ricevuta per errore, si prega di provvedere alla distruzione dell’intero messaggio e di informare tempestivamente il mittente. Grazie.

This email (and any files transmitted with it) includes Terna Group information and is intended solely for the use of the recipients to whom it is addressed. Please note that disclosing the contents of this email is strictly prohibited without Terna’s express consent. Please notify the sender immediately if you have received this e-mail by mistake and delete this e-mail from your system. Thank you.
